version: 2

sources:
  - name: river_data_analytics
    database: dm2-water
    schema: river_data_analytics
    tables:
      - name: live_weather
      - name: river_weather  # required for the new insights

models:
  - name: avg_temperature
    description: "Daily weather summary"
    columns:
      - name: city
        tests:
          - not_null
      - name: avg_temp
        tests:
          - not_null

  - name: daily_environmental_summary
    description: "Aggregated daily values for all river and weather metrics"

  - name: river_weather_correlation
    description: "Correlations between weather parameters and river conditions"

  - name: temp_oxygen_relationship
    description: "Impact of temperature on dissolved oxygen levels"

  - name: wind_vs_water_quality
    description: "Grouped metrics like turbidity and pH by windspeed bands"

  - name: environmental_health_score
    description: "Composite index score representing overall river environmental health"
