version: 2

sources:
  - name: river_data_analytics
    database: dm2-water
    schema: river_data_analytics
    tables:
      - name: live_weather

models:
  - name: avg_temperature
    description: "Daily weather summary"
    columns:
      - name: city
        tests:
          - not_null
      - name: avg_temp
        tests:
          - not_null
