version: 2

sources:
  - name: river_data_analytics
    database: dm2-water
    schema: river_data_analytics
    tables:
      - name: live_weather
      - name: river_weather

models:
  - name: stg_live_weather
    description: "Cleaned and renamed fields from raw live_weather table"
    columns:
      - name: date
        tests: [not_null]
      - name: temperature
        tests: [not_null]
      - name: city
        tests: [not_null]

  - name: stg_river_weather
    description: "Cleaned and standardized fields from raw river_weather table"
    columns:
      - name: date
        tests:
          - not_null:
              where: "weather_temperature IS NOT NULL"

      - name: River_Temperature
        tests: []
        
      - name: weather_temperature
        tests:
          - not_null

      - name: humidity
        tests:
          - not_null:
              where: "weather_temperature IS NOT NULL"

      - name: wind_speed
        tests:
          - not_null:
              where: "weather_temperature IS NOT NULL"

      - name: ph
        tests: []

      - name: turbidity
        tests: []

      - name: dissolved_oxygen
        tests: []

      - name: chlorophyll
        tests: []

  - name: int_weather_river_joined
    description: "Joined and preprocessed table combining river and weather data"
    columns:
      - name: date
        tests: [not_null]
      - name: city
        tests: [not_null]

  - name: daily_environmental_summary
    description: "Daily average, min, max values for key environmental indicators"
    columns:
      - name: date
        tests: [not_null, unique]

  - name: river_weather_correlation
    description: "Computed correlation between river quality metrics and weather indicators"
    columns:
      - name: correlation_type
        tests: []

  - name: temp_oxygen_relationship
    description: "Analyzes how temperature variations impact oxygen saturation"
    columns:
      - name: date
        tests: [not_null]

  - name: wind_vs_water_quality
    description: "Compares water quality metrics across windspeed bands"
    columns:
      - name: wind_band
        tests: [not_null]

  - name: environmental_health_score
    description: "Composite score based on normalized water quality metrics"
    columns:
      - name: score
        tests: []

  - name: avg_temperature
    description: "Daily average temperature per city (from live_weather)"
    columns:
      - name: city
        tests: []
      - name: avg_temp
        tests: []
